version: "3.8"
services:
       login-app:
           container_name: login-app
           image: hosnikadour/app-nodejs 
           restart: always
           build: .
           ports:
             - "4000:4000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'